# Generated by Django 5.0.2 on 2024-03-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_town_product_category_product_town'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
